name: Continuous Integration
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test212:
    name: Test (Scala 2.12)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: sbt
      - run: npm install jsdom@12.2.0
      - run: docker run -d -p 8080:8080 julienrf/endpoints4s-stubserver:1.1.0
      - run: sbt "++ 2.12 test"

  test213:
    name: Test (Scala 2.13)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: sbt
      - run: npm install jsdom@12.2.0
      - run: sudo apt-get install graphviz
      - run: docker run -d -p 8080:8080 julienrf/endpoints4s-stubserver:1.1.0
      - run: sbt "++ 2.13 ;coverage ;test ;coverageReport ;coverageAggregate ;documentation/makeSite"
      - run: bash <(curl -s https://codecov.io/bash)

  test3:
    name: Compile (Scala 3)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: sbt
      - run: npm install jsdom@12.2.0
      - run: sbt "++ 3 compile"

  versionPolicy:
    name: Check versioning policy and code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: sbt
      - run: sbt versionPolicyCheck scalafmtCheck