name: Release
on:
  push:
    tags: ["v*"]

jobs:

  publish:
    runs-on: ubuntu-20.04
    env:
      SBT_NATIVE_CLIENT: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: sbt
      - run: sbt versionCheck
      - run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      - name: Generate site
        run: sbt documentation/makeSite
      - uses: JamesIves/github-pages-deploy-action@4.1.9
        with:
          branch: gh-pages
          folder: documentation/target/site
